# NPM
alias ns='npm start'
alias nw='npm run watch'
alias nd='npm run dev'
alias nt='npm test'
alias nwt='npm run watch-test'
alias nde='npm run decryptEnv'
alias nee='npm run encryptEnv'
alias ndel='npm run decryptEnvLocal'
alias neel='npm run encryptEnvLocal'
